languageCode = "en-us"
title = "David Paskevic's blog"
baseURL = "https://casept.github.io/"
theme = "hugo-theme-pixyll"

[params]
  description = "My blog, which I may or may not update from time to time."
  author = "casept"
